<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="5" ignored="0" total="10" passed="5">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="6806" started-at="2021-01-30T19:27:07Z" finished-at="2021-01-30T19:27:14Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="6806" started-at="2021-01-30T19:27:07Z" finished-at="2021-01-30T19:27:14Z">
      <class name="com.eo.tests.PostNewUser">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.eo.tests.PostNewUser@2e1d27ba]" name="setUp" is-config="true" duration-ms="440" started-at="2021-01-30T19:27:08Z" finished-at="2021-01-30T19:27:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="createNewUser_TC004(java.lang.String, java.lang.String)[pri:0, instance:com.eo.tests.PostNewUser@2e1d27ba]" name="createNewUser_TC004" duration-ms="3389" started-at="2021-01-30T19:27:09Z" data-provider="getUserData_TC004" finished-at="2021-01-30T19:27:12Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[xyz]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[tester]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createNewUser_TC004 -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.eo.tests.PostNewUser@2e1d27ba]" name="setUp" is-config="true" duration-ms="1" started-at="2021-01-30T19:27:12Z" finished-at="2021-01-30T19:27:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="createNewUser_TC004(java.lang.String, java.lang.String)[pri:0, instance:com.eo.tests.PostNewUser@2e1d27ba]" name="createNewUser_TC004" duration-ms="262" started-at="2021-01-30T19:27:12Z" data-provider="getUserData_TC004" finished-at="2021-01-30T19:27:13Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Urmila]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[tester]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createNewUser_TC004 -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.eo.tests.PostNewUser@2e1d27ba]" name="setUp" is-config="true" duration-ms="0" started-at="2021-01-30T19:27:13Z" finished-at="2021-01-30T19:27:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="createNewUser_TC004(java.lang.String, java.lang.String)[pri:0, instance:com.eo.tests.PostNewUser@2e1d27ba]" name="createNewUser_TC004" duration-ms="247" started-at="2021-01-30T19:27:13Z" data-provider="getUserData_TC004" finished-at="2021-01-30T19:27:13Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[123]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[tester]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createNewUser_TC004 -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.eo.tests.PostNewUser@2e1d27ba]" name="setUp" is-config="true" duration-ms="1" started-at="2021-01-30T19:27:13Z" finished-at="2021-01-30T19:27:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="createNewUserIncorrectEP_TC005()[pri:1, instance:com.eo.tests.PostNewUser@2e1d27ba]" name="createNewUserIncorrectEP_TC005" duration-ms="181" started-at="2021-01-30T19:27:13Z" finished-at="2021-01-30T19:27:13Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [404] but found [201]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [404] but found [201]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at org.testng.Assert.assertEquals(Assert.java:662)
at com.eo.tests.PostNewUser.createNewUserIncorrectEP_TC005(PostNewUser.java:82)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createNewUserIncorrectEP_TC005 -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.eo.tests.PostNewUser@2e1d27ba]" name="setUp" is-config="true" duration-ms="0" started-at="2021-01-30T19:27:13Z" finished-at="2021-01-30T19:27:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="createNewUserIncorrectParamValues_TC006_007(java.lang.Object, java.lang.Object)[pri:2, instance:com.eo.tests.PostNewUser@2e1d27ba]" name="createNewUserIncorrectParamValues_TC006_007" duration-ms="165" started-at="2021-01-30T19:27:13Z" data-provider="getUserData_TC006" finished-at="2021-01-30T19:27:14Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[123]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[456]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [400] but found [201]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [400] but found [201]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at org.testng.Assert.assertEquals(Assert.java:662)
at com.eo.tests.PostNewUser.createNewUserIncorrectParamValues_TC006_007(PostNewUser.java:103)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createNewUserIncorrectParamValues_TC006_007 -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.eo.tests.PostNewUser@2e1d27ba]" name="setUp" is-config="true" duration-ms="1" started-at="2021-01-30T19:27:14Z" finished-at="2021-01-30T19:27:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="createNewUserIncorrectParamValues_TC006_007(java.lang.Object, java.lang.Object)[pri:2, instance:com.eo.tests.PostNewUser@2e1d27ba]" name="createNewUserIncorrectParamValues_TC006_007" duration-ms="153" started-at="2021-01-30T19:27:14Z" data-provider="getUserData_TC006" finished-at="2021-01-30T19:27:14Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[$%*]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[@&^]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [400] but found [201]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [400] but found [201]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at org.testng.Assert.assertEquals(Assert.java:662)
at com.eo.tests.PostNewUser.createNewUserIncorrectParamValues_TC006_007(PostNewUser.java:103)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createNewUserIncorrectParamValues_TC006_007 -->
      </class> <!-- com.eo.tests.PostNewUser -->
      <class name="com.eo.tests.GetUsersPrintHeaders">
        <test-method status="PASS" signature="getAllHeadersPrint()[pri:0, instance:com.eo.tests.GetUsersPrintHeaders@61d6015a]" name="getAllHeadersPrint" duration-ms="136" started-at="2021-01-30T19:27:13Z" finished-at="2021-01-30T19:27:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getAllHeadersPrint -->
      </class> <!-- com.eo.tests.GetUsersPrintHeaders -->
      <class name="com.eo.tests.GetUsers">
        <test-method status="PASS" signature="getUsersValidEP_TC001()[pri:0, instance:com.eo.tests.GetUsers@2525ff7e]" name="getUsersValidEP_TC001" duration-ms="137" started-at="2021-01-30T19:27:13Z" finished-at="2021-01-30T19:27:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getUsersValidEP_TC001 -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.eo.tests.GetUsers@2525ff7e]" name="setUp" is-config="true" duration-ms="0" started-at="2021-01-30T19:27:13Z" finished-at="2021-01-30T19:27:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.eo.tests.GetUsers@2525ff7e]" name="setUp" is-config="true" duration-ms="1" started-at="2021-01-30T19:27:13Z" finished-at="2021-01-30T19:27:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="getUsersCount_TC002()[pri:1, instance:com.eo.tests.GetUsers@2525ff7e]" name="getUsersCount_TC002" duration-ms="144" started-at="2021-01-30T19:27:13Z" finished-at="2021-01-30T19:27:13Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [12] but found [6]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [12] but found [6]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at org.testng.Assert.assertEquals(Assert.java:662)
at com.eo.tests.GetUsers.getUsersCount_TC002(GetUsers.java:77)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getUsersCount_TC002 -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.eo.tests.GetUsers@2525ff7e]" name="setUp" is-config="true" duration-ms="1" started-at="2021-01-30T19:27:14Z" finished-at="2021-01-30T19:27:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="getUsersIncorrectEP_TC003()[pri:2, instance:com.eo.tests.GetUsers@2525ff7e]" name="getUsersIncorrectEP_TC003" duration-ms="111" started-at="2021-01-30T19:27:14Z" finished-at="2021-01-30T19:27:14Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [404] but found [200]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [404] but found [200]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at org.testng.Assert.assertEquals(Assert.java:662)
at com.eo.tests.GetUsers.getUsersIncorrectEP_TC003(GetUsers.java:93)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getUsersIncorrectEP_TC003 -->
      </class> <!-- com.eo.tests.GetUsers -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
